### ISSUE TITLE
Tectonicus 2.2.0 doesn't run on Mac OSX Yosemite with Java 8

### ISSUE THREAD

**Issue by mcw0933** [tectonicus/tectonicus#57]
I was getting the following:

Using existing player skin cache
Creating player icon assembler
Initialising display...
**java.lang.UnsatisfiedLinkError: Can't load library: /Users/matt/.tectonicus/native/liblwjgl.dylib**
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1083)
	at org.lwjgl.Sys$1.run(Sys.java:70)

Looking in that path, I have no .dylib files, only .jnilib files.  I tried renaming them as recommended [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1260577-tectonicus-v2-07-expanded-mod-support?page=232) but it didn't work.

I uninstalled Java 8u25 and installed the Java 7u71 [JRE](https://www.java.com/en/download/manual_java7.jsp#mac) and [JDK](http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html) from the Oracle site and now I'm back in business.

**Comment by rbartleman** [comment]
This error is fixed with a symlink 
`ln -s ~/.tectonicus/native/liblwjgl.jnilib ~/.tectonicus/native/liblwjgl.dylib` 
and set extractLwjglNatives = "false" in tweeks.

**Comment by rbartleman** [comment]
Looks like making the symlink in the same directory as the jar is working 100% on another machine.

`ln -s /path/to/tectonicus/folder/with/jar/liblwjgl.jnilib ~/.tectonicus/native/liblwjgl.dylib`

Looks like it was overwriting the symlink when it ran in my other example.

**Comment by rbartleman** [comment]
Use a symlink `ln -s ~/.tectonicus/native/liblwjgl.jnilib ~/Documents/MC\ Stuff/liblwjgl.dylib`

I have the tectonicus.jar in Documents/MC Stuff/tectonicus.jar. Change your path to where yours is.
Then add
`	<tweeks
		extractLwjglNatives = "false"
		forceLoadAwt = "false"
		force32BitNatives = "false"
		force64BitNatives = "true"
	/>
` after the </map> in your config.

**Comment by skoeven** [comment]
Hopefully this should now be fixed.  f90910f96e2dc4dee46f566e438d0997f2c9c171

**Comment by toyjack** [comment]
@skoeven Nope, didn't fix it in El Capitan.
Still dumping lots of files like something from windows.
```
total 5296
drwxr-xr-x  14 toyjack  staff     476 11 13 02:51 .
drwxr-xr-x   3 toyjack  staff     102 11 13 02:51 ..
-rw-r--r--   1 toyjack  staff   61952 11 13 02:51 jinput-dx8.dll
-rw-r--r--   1 toyjack  staff   65024 11 13 02:51 jinput-dx8_64.dll
-rw-r--r--   1 toyjack  staff   59392 11 13 02:51 jinput-raw.dll
-rw-r--r--   1 toyjack  staff   62464 11 13 02:51 jinput-raw_64.dll
-rw-r--r--   1 toyjack  staff   13824 11 13 02:51 libjinput-linux.so
-rw-r--r--   1 toyjack  staff   14512 11 13 02:51 libjinput-linux64.so
-rw-r--r--   1 toyjack  staff   64608 11 13 02:51 libjinput-osx.jnilib
-rw-r--r--   1 toyjack  staff  927456 11 13 02:51 liblwjgl.jnilib
-rw-r--r--   1 toyjack  staff  374632 11 13 02:51 liblwjgl.so
-rw-r--r--   1 toyjack  staff  445368 11 13 02:51 liblwjgl64.so
-rw-r--r--   1 toyjack  staff  294912 11 13 02:51 lwjgl.dll
-rw-r--r--   1 toyjack  staff  306176 11 13 02:51 lwjgl64.dll
```

**Comment by skoeven** [comment]
Are you using Tectonicus v2.20?  The fix was committed to the repository after v2.20 and you would need to compile the code yourself if you want to test it or wait until I upload an official v2.21 release (hopefully sometime in the next few weeks).
